version: 2.1
defaults: &defaults
  docker:
    - image: amazon/aws-cli
  working_directory: ~/
jobs:
  print_env_vars:
    <<: *defaults
    steps:
      - checkout
      - run: printenv
      - run: echo $AWS_ACCESS_KEY_ID
      - run: echo $AWS_SECRET_ACCESS_KEY
      - run: echo $AWS_DEFAULT_REGION
  create_infrastructure:
    <<: *defaults
    steps:
      - run: |
          echo "[defaul]" > ~/.aws/credentials 
          echo "aws_access_key_id="$AWS_ACCESS_KEY_ID >> ~/.aws/credentials
          echo "aws_secret_access_key="$AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
          echo "region="$AWS_DEFAULT_REGION >> ~/.aws/config
      - run: aws cloudformation create-stack --stack-name TestStack --template-body template.yml  --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
workflows:
  infra:
    jobs:
      - print_env_vars
      - create_infrastructure
