# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: alpine:latest
  working_directory: ~/
print_pipeline_id: &print_pipeline_id
  steps:
    - run:
        name: Reusable Command to print workflowid
        command: echo $CIRCLE_WORKFLOW_ID
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    environment:
      MSG_1: "Hello"
    <<: *defaults
    steps:
      # - checkout
      - run:
          name: Print Hello
          command: echo $MSG_1
  print_world:
    environment:
      MSG_1: "World"
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Print Hello
          command: echo $MSG_1
  print_env_vars:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Print Project Details
          command: echo $PROJECT_NAME
      - run: echo $CIRCLE_USERNAME
      - run: echo $CIRCLE_SHA1
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: printenv
  save_hello_world_output:
    <<: *defaults
    steps:
      - run:
          name: Persist Output
          command: echo $MSG_1 > out.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - out.txt
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: |
          pwd
          ls -lah
      - run:
          name: Read file
          command: cat out.txt

  print_workflow_id:
    <<: *defaults
    <<: *print_pipeline_id

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      # - welcome/run
      # - print_hello
      # - print_world:
      #     requires:
      #       - print_hello
      # - print_env_vars  
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print_workflow_id
