# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    environment:
      MSG_1: "Hello"
    docker: 
    - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Print Hello
          command: echo $MSG_1
  print_world:
    environment:
      MSG_1: "World"
    docker: 
    - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Print Hello
          command: echo $MSG_1
  print_env_vars:
    docker: 
    - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Print Project Details
          command: echo $PROJECT_NAME
      - run: echo $CIRCLE_USERNAME
      - run: echo $CIRCLE_SHA1
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: printenv
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_env_vars  
