version: 2.1
defaults: &defaults
  docker:
    - image: amazon/aws-cli
  working_directory: ~/
jobs:
  create_infrastructure:
    <<: *defaults
    steps:
      - checkout
      - run: aws cloudformation deploy --stack-name TestStack --template-file template.yml  --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
  populate_inventory:
    <<: *defaults
    steps:
      - run: |
          echo [all] >> inventory.txt
          aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Project,Values=TestServer" --output text >> inventory.txt
      - save_cache:
          key: inventory
          paths: ~/inventory.txt
  deploy_job:
    docker: 
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fc:9a:a5:f0:bb:74:6a:59:ae:ba:f7:1d:55:24:22:08"
      - run: apk add --update ansible 
      - restore_cache:
          key: inventory
      - run: ansible-playbook -i inventory.txt main.yml # might need to reference the above ssh key?
workflows:
  infra:
    jobs:
      - create_infrastructure
      - deploy_job:
          requires:
            - create_infrastructure
