version: 2.1
defaults: &defaults
  docker:
    - image: amazon/aws-cli
  working_directory: ~/
jobs:
  create_infrastructure:
    <<: *defaults
    steps:
      - checkout
      - run: aws cloudformation deploy -stack-name TestStack --template-file template.yml  --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
workflows:
  infra:
    jobs:
      - create_infrastructure
